version: "3.5"

services:
  bot:
    container_name: support_bot
    build: .
    env_file:
      - ".env"
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - .:/app/
    command: python3 app.py
